### ISSUE TITLE
General fixes in README

### ISSUE THREAD

**Issue by cvigilv** [Dan7h3x/NvimPy#3]
Hi!

First of all, really cool project. I just wanted to add this issue to list some problems you have with the README:

- [x] Videos are corrupted, therefore can't be seen by possible users
- [x] You have typos scattered around the README file. I would pass the text contents through a grammar checker or ChatGPT to solve this.
- [x] #4
- [ ] I would add some images to go with the "Some highlights"

Hope this helps! Rooting for this project to grow. Look cool!

**Comment by Dan7h3x** [comment]
I'm grateful for your help.

Let's get NvimPy to it's maximum potential together🙏❤️
